# Keras 101

Usaremos o Keras com um backend Tensorflow para ver o básico de Deep Learning!

## Imports



In [1]:
#Novidade - SciKit Learn
import numpy as np
import sklearn
#Suprimir Warnings 
import warnings
warnings.filterwarnings('ignore')

## Dataset

Usaremos um dataset de cédulas, os dados são características de imagem derivadas de imagens reais de 400x400 pixels. Notem que o dataset não consiste em imagens reais, outrossim características (features) das imagens.

_____
Mais informações:

https://archive.ics.uci.edu/ml/datasets/banknote+authentication

## Carregando o Dataset

Os dados estão na pasta 'dados', carregue de acordo.

In [2]:
from numpy import genfromtxt
dados = genfromtxt('dados/bank_note_data.txt', delimiter=',')

In [3]:
dados

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = dados[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = dados[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

## Dividindo os Dados entre Treinamento e Teste

Agora dividiremos os dados entre dois sets - treina e teste. Na vida real, temos um set adicional: validação. Mas iremos simplificar as coisas por enquanto...

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_treina, X_teste, y_treina, y_teste = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
X_treina

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [12]:
X_teste

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [13]:
y_treina

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 1., 0.

In [14]:
y_teste

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 0.

## Padronizando os Dados

Normalmente, você garante melhor performance quando padronia os dados. Padronizar normalmente consiste em normalizar os valores de modo a caber em um certo range, como 0 a 1 ou -1 a 1.

A bibilioteca Scikit Learn tem uma função para isso:

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
scaler_object = MinMaxScaler()

In [17]:
scaler_object.fit(X_treina)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [18]:
scaled_X_treina = scaler_object.transform(X_treina)

In [19]:
scaled_X_teste = scaler_object.transform(X_teste)

Agora temos os dados normalizados!

In [20]:
X_treina.max()

17.9274

In [21]:
scaled_X_treina.max()

1.0000000000000002

In [22]:
X_treina

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [23]:
scaled_X_treina

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

## Criando a Rede Neural com o Keras

In [28]:
from keras.models import Sequential
from keras.layers import Dense

In [29]:
# Cria o modelo
modelo = Sequential()
# 8 Neurons, com 4 características de entrada.
modelo.add(Dense(4, input_dim=4, activation='relu'))
# Adiciona outra camada densamente conectada
modelo.add(Dense(8, activation='relu'))
# Última camada é uma função sigmóide com saída 0 ou 1 (label)
modelo.add(Dense(1, activation='sigmoid'))

### Compilar o Modelo

In [31]:
modelo.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

## Treina o Modelo

In [32]:
# Teste outros valores de iteração - epochs
modelo.fit(scaled_X_treina,y_treina,epochs=50, verbose=2)

W0826 10:21:14.370483 140599257765696 deprecation_wrapper.py:119] From /home/cursocv/.virtualenvs/cursocv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/50
 - 1s - loss: 0.6983 - acc: 0.4908
Epoch 2/50
 - 0s - loss: 0.6636 - acc: 0.6888
Epoch 3/50
 - 0s - loss: 0.6506 - acc: 0.5560
Epoch 4/50
 - 0s - loss: 0.6386 - acc: 0.5626
Epoch 5/50
 - 0s - loss: 0.6285 - acc: 0.5811
Epoch 6/50
 - 0s - loss: 0.6197 - acc: 0.6355
Epoch 7/50
 - 0s - loss: 0.6104 - acc: 0.6670
Epoch 8/50
 - 0s - loss: 0.6005 - acc: 0.7193
Epoch 9/50
 - 0s - loss: 0.5894 - acc: 0.7399
Epoch 10/50
 - 0s - loss: 0.5780 - acc: 0.7573
Epoch 11/50
 - 0s - loss: 0.5671 - acc: 0.7617
Epoch 12/50
 - 0s - loss: 0.5549 - acc: 0.7748
Epoch 13/50
 - 0s - loss: 0.5435 - acc: 0.7704
Epoch 14/50
 - 0s - loss: 0.5310 - acc: 0.7911
Epoch 15/50
 - 0s - loss: 0.5187 - acc: 0.7987
Epoch 16/50
 - 0s - loss: 0.5067 - acc: 0.7987
Epoch 17/50
 - 0s - loss: 0.4933 - acc: 0.8150
Epoch 18/50
 - 0s - loss: 0.4804 - acc: 0.8205
Epoch 19/50
 - 0s - loss: 0.4668 - acc: 0.8248
Epoch 20/50
 - 0s - loss: 0.4531 - acc: 0.8335
Epoch 21/50
 - 0s - loss: 0.4395 - acc: 0.8585
Epoch 22/50
 - 0s - lo

## Prevendo novos dados

Vamos ver como nosso modelo se comporta prevendo **novos dados**. Lembrando que nosso modelo nunca viu os dados testes! Trata-se do mesmo processo com novos dados. Por exemplo, uma nova cedula a ser analisada.

In [34]:
scaled_X_teste

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.76115065, 0.62415668, 0.27251204, 0.83616757],
       [0.9047516 , 0.90329171, 0.03658247, 0.42267079],
       [0.49296526, 0.86039507, 0.06714046, 0.1622583 ]])

In [36]:
# "Cospe" probabilidades por default.
# model.predict(scaled_X_teste)

In [38]:
modelo.predict_classes(scaled_X_teste)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    

# Testando a Performance do Modelo

In [40]:
modelo.metrics_names

['loss', 'acc']

In [41]:
modelo.evaluate(x=scaled_X_teste,y=y_teste)

453/453 [==============================] - 0s 319us/step


[0.16995235716730817, 0.9558498896247241]

In [42]:
from sklearn.metrics import confusion_matrix,classification_report

In [43]:
predictions = model.predict_classes(scaled_X_teste)

In [44]:
confusion_matrix(y_teste,predictions)

array([[248,   9],
       [107,  89]])

In [45]:
print(classification_report(y_teste,predictions))

              precision    recall  f1-score   support

         0.0       0.70      0.96      0.81       257
         1.0       0.91      0.45      0.61       196

    accuracy                           0.74       453
   macro avg       0.80      0.71      0.71       453
weighted avg       0.79      0.74      0.72       453



## Savlvando e Carregando Modelos

Agora que temos um modelo treinado, vamos ver como salvar e carregar.

In [46]:
modelo.save('meumodelo.h5')

In [47]:
from keras.models import load_model

In [50]:
novomodelo = load_model('meumodelo.h5')

In [51]:
novomodelo.predict_classes(X_teste)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
    